QLSQ/Models/DaoTaoNewViewModel.cs
using QLSQ.ViewModel.Catalogs.New;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QLSQ.WebApp.Models
{
    public class DaoTaoNewViewModel
    {
        public List<NewDetailsViewModel> ListDaoTaoNew { get; set; }
    }
}

QLSQ/Controllers/DaoTaoNewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QLSQ.ApiIntergration;
using QLSQ.WebApp.Models;

namespace QLSQ.WebApp.Controllers
{
    public class DaoTaoNewController : Controller
    {
        public readonly INewApiClient _newApiClient;
        public DaoTaoNewController(INewApiClient newApiClient)
        {
            _newApiClient = newApiClient;
        }
        public async Task<IActionResult> Index()
        {
            var listDaoTaoNew = await _newApiClient.GetListDaoTaoNew();
            var daoTaoNewVM = new DaoTaoNewViewModel()
            {
                ListDaoTaoNew = listDaoTaoNew.ResultObj
            };
            return View(daoTaoNewVM);
        }
    }
}

QLSQ/Controllers/DetailNewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QLSQ.ApiIntergration;
using QLSQ.WebApp.Models;

namespace QLSQ.WebApp.Controllers
{
    public class DetailNewController : Controller
    {
        public readonly INewApiClient _newApiClient;
        public DetailNewController(INewApiClient newApiClient)
        {
            _newApiClient = newApiClient;
        }
        public async Task<IActionResult> Index(int NewID)
        {
            var result = await _newApiClient.DetailNew(NewID);
            var listMostViewNew = await _newApiClient.GetMostViewNew();
            var detailNewVM = new DetailNewViewModel()
            {
                NewID = NewID,
                NewDatePost = result.ResultObj.NewDatePost,
                NewName = result.ResultObj.NewName,
                NewContent = result.ResultObj.NewContent,
                ImagePath = result.ResultObj.ImagePath,
                NewCatetoryID = result.ResultObj.NewCatetoryID,
                NewCatetoryName = result.ResultObj.NewCatetoryName,
                ListMostViewNew = listMostViewNew.ResultObj
            };
            var listRelatedNew = await _newApiClient.GetRelatedNew(detailNewVM.NewCatetoryID);
            detailNewVM.ListRelatedNew = listRelatedNew.ResultObj;
            return View(detailNewVM);
        }
    }
}

QLSQ/Views/DaoTaoNew/Index.cshtml
@model QLSQ.WebApp.Models.DaoTaoNewViewModel
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@{
    ViewData["Title"] = "Index";
}

<div class="row mt-5">
    <div class="col-sm-12">
        <h5 class="text-muted font-weight-medium mb-3">Đào tạo</h5>
    </div>
</div>
<div class="row mb-4">
    @foreach (var news in Model.ListDaoTaoNew)
    {
        <div class="col-sm-3  mb-5 mb-sm-2">
            <div class="position-relative image-hover">
                <img src="@Configuration["BaseAddress"]/new-image/@news.ImagePath"
                     class="img-fluid"
                     alt="world-news" />
                <span class="thumb-title">@news.NewCatetoryName</span>
            </div>
            <h5 class="font-weight-600 mt-3">
                <a asp-controller="DetailNew" asp-action="Index" asp-route-NewID="@news.NewID" class="text-dark">@news.NewName</a>

            </h5>
            <p class="fs-15 font-weight-normal">
                @Html.Raw(news.NewContent.Substring(0, 50)) ...
            </p>
        </div>
    }
</div>